name: college_jewelry_store
description: A new
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  page_transition: ^2.0.9
  # format DateTime
  intl: ^0.17.0
  #database storage
  sqflite: ^2.1.0+1
  shared_preferences: ^2.0.15
  email_validator: '^2.1.16'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/empty_box.png
    - assets/playstore.png
    - assets/rings/golden_amethyst_ring.jpg
    - assets/rings/golden_diamond_ring.jpg
    - assets/rings/golden_emerald_ring.jpg
    - assets/rings/golden_ring.jpg
    - assets/rings/golden_ruby_ring.jpg
    - assets/rings/golden_sapphire_ring.jpg
    - assets/rings/platinum_amethyst_ring.png
    - assets/rings/platinum_diamond_ring.png
    - assets/rings/platinum_emerald_ring.jpg
    - assets/rings/platinum_ring.jpg
    - assets/rings/platinum_ruby_ring.jpg
    - assets/rings/platinum_sapphire_ring.png
    - assets/rings/silver_amethyst_ring.png
    - assets/rings/silver_diamond_ring.png
    - assets/rings/silver_emerald_ring.jpg
    - assets/rings/silver_ring.png
    - assets/rings/silver_ruby_ring.jpeg
    - assets/rings/silver_sapphire_ring.png
    - assets/bracelets/golden_amethyst_bracelet.jpg
    - assets/bracelets/golden_bracelet.jpg
    - assets/bracelets/golden_diamond_bracelet.jpg
    - assets/bracelets/golden_emerald_bracelet.jpg
    - assets/bracelets/golden_ruby_bracelet.jpg
    - assets/bracelets/golden_sapphire_bracelet.jpg
    - assets/bracelets/platinum_amethyst_bracelet.jpg
    - assets/bracelets/platinum_bracelet.jpg
    - assets/bracelets/platinum_diamond_bracelet.jpg
    - assets/bracelets/platinum_emerald_bracelet.jpg
    - assets/bracelets/platinum_ruby_bracelet.jpg
    - assets/bracelets/platinum_sapphire_bracelet.png
    - assets/bracelets/silver_amethyst_bracelet.jpg
    - assets/bracelets/silver_bracelet.jpg
    - assets/bracelets/silver_diamond_bracelet.png
    - assets/bracelets/silver_emerald_bracelet.png
    - assets/bracelets/silver_ruby_bracelet.jpg
    - assets/bracelets/silver_sapphire_bracelet.jpg
    - assets/brooches/golden_amethyst_brooch.jpg
    - assets/brooches/golden_brooch.jpg
    - assets/brooches/golden_diamond_brooch.jpg
    - assets/brooches/golden_emerald_brooch.jpg
    - assets/brooches/golden_ruby_brooch.jpeg
    - assets/brooches/golden_sapphire_brooch.jpg
    - assets/brooches/platinum_amethyst_brooch.jpg
    - assets/brooches/platinum_brooch.jpg
    - assets/brooches/platinum_diamond_brooch.jpg
    - assets/brooches/platinum_emerald_brooch.jpg
    - assets/brooches/platinum_ruby_brooch.jpg
    - assets/brooches/platinum_sapphire_brooch.jpg
    - assets/brooches/silver_amethyst_brooch.jpg
    - assets/brooches/silver_brooch.jpg
    - assets/brooches/silver_diamond_brooch.jpg
    - assets/brooches/silver_emerald_brooch.jpg
    - assets/brooches/silver_ruby_brooch.jpg
    - assets/brooches/silver_sapphire_brooch.jpg
    - assets/necklace/golden_amethyst_necklace.jpg
    - assets/necklace/golden_diamond_necklace.jpeg
    - assets/necklace/golden_emerald_necklace.jpg
    - assets/necklace/golden_necklace.png
    - assets/necklace/golden_ruby_necklace.png
    - assets/necklace/golden_sapphire_necklace.jpeg
    - assets/necklace/platinum_amethyst_necklace.jpg
    - assets/necklace/platinum_diamond_necklace.jpg
    - assets/necklace/platinum_emerald_necklace.jpg
    - assets/necklace/platinum_necklace.png
    - assets/necklace/platinum_ruby_necklace.jpg
    - assets/necklace/platinum_sapphire_necklace.jpg
    - assets/necklace/silver_amethyst_necklace.jpg
    - assets/necklace/silver_diamond_necklace.jpg
    - assets/necklace/silver_emerald_necklace.jpeg
    - assets/necklace/silver_necklace.png
    - assets/necklace/silver_ruby_necklace.png
    - assets/necklace/silver_sapphire_necklace.jpg
    - assets/earrings/golden_amethyst_earrings.jpg
    - assets/earrings/golden_diamond_earrings.png
    - assets/earrings/golden_earrings.jpg
    - assets/earrings/golden_emerald_earrings.jpg
    - assets/earrings/golden_ruby_earrings.jpg
    - assets/earrings/golden_sapphire_earrings.jpeg
    - assets/earrings/platinum_amethyst_earrings.jpg
    - assets/earrings/platinum_diamond_earrings.jpg
    - assets/earrings/platinum_earrings.jpg
    - assets/earrings/platinum_emerald_earrings.jpg
    - assets/earrings/platinum_ruby_earrings.jpg
    - assets/earrings/platinum_sapphire_earrings.jpg
    - assets/earrings/silver_amethyst_earrings.png
    - assets/earrings/silver_diamond_earrings.jpg
    - assets/earrings/silver_earrings.jpg
    - assets/earrings/silver_emerald_earrings.png
    - assets/earrings/silver_ruby_earrings.jpg
    - assets/earrings/silver_sapphire_earrings.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700